---
- hosts: all
  become: yes
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: Install docker and its dependecies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    notify:
      - docker status
  - name: Set up the Docker daemon
    shell: |
       cat > /etc/docker/daemon.json <<EOF
       {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
       }
       EOF
  - name: Create systemd directory for daemon
    file:
       path: /etc/systemd/system/docker.service.d
       state: directory

  - name: just force systemd to reread configs
    systemd:
       daemon_reload: yes

  - name: restart Docker
    systemd:
      name: docker
      state: restarted

  handlers:
    - name: docker status
      service: name=docker state=started
